
# ?? ?? ??
spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    enabled: true
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:mysql://localhost:3306/OEasy?useSSL=false&serverTimezone=Asia/Seoul
    username: user
    password: "!db1234"
kakao:
  client:
    id: 9d0f8b32ee577d8830b4a174ef9a5f30
    secret: 0jKlaFpf71RfuZYD8f23maTrdhoRCBxo
  redirect:
    url: http://localhost:8080/kakao/callback
---
# ??? (dev ??)
spring:
  config:
    activate:
      on-profile: dev
  kafka:
    consumer:
      group-id: weather_group
    bootstrap-servers: 54.180.247.119:9092
  security:
    user:
      password: '1234123412341234'
      name: 'admin'
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: 'true'
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: '!!OEasy!!'
    username: admin
    url: jdbc:mysql:aws://oeasy.cr4qy08gwh2q.ap-northeast-2.rds.amazonaws.com:3306/OEasy?useSSL=false&serverTimezone=Asia/Seoul
  application:
    name: OEasy
springdoc:
  swagger-ui:
    doc-expansion: none
    enabled: 'true'
    path: /swagger-ui-custom.html
    display-request-duration: 'true'
    groups-order: ASC
    operations-sorter: alpha
    tags-sorter: alpha
  api-docs:
    path: /api-docs
    groups:
      enabled: 'true'
  cache:
    disabled: 'true'
  model-and-view-allowed: 'true'
kakao:
  client:
    id: 9d0f8b32ee577d8830b4a174ef9a5f30
    secret: 0jKlaFpf71RfuZYD8f23maTrdhoRCBxo
  redirect:
    url: http://localhost:8080/kakao/callback
weather:
  api:
    key: f01dc3bd3f08146036654aca4d722036
